// 服务端首次启动时写入数据库的种子内容（与前端 demo 内容一致）
const SEED_POSTS = [
  { id: 's1', cat: 'festival', tall: 1, author: '散帅节筹委会', avatar: '🌞',
    title: '8·3 国际散帅节｜今天，散步、散心、散个帅！',
    body: '一年一度的国际散帅节（International Sunshine Day）来啦！\n\n口号：三月八号是女神节，八月三号轮到咱散帅节 😎\n今天的正确打开方式——放下手机去晒晒太阳，约上兄弟散散步、撸个铁、钓个鱼，做一个阳光散帅的男人。\n\n发帖带话题 #我的散帅时刻 ，抽 10 位帅哥送定制蓝书周边！',
    tags: ['我的散帅时刻', '国际散帅节', '散帅一夏'], likes: 1288, collects: 402, festival: 1,
    comments: [{ author: '老铁健身局', avatar: '💪', text: '散帅节快乐！已撸铁打卡 💯' }, { author: '夜钓王阿强', avatar: '🎣', text: '今晚夜钓，散帅到天亮' }] },
  { id: 's2', cat: 'fitness', author: '老铁健身局', avatar: '💪',
    title: '新手三个月练胸，从平板到上斜的血泪经验',
    body: '别一上来就冲大重量。先把动作做标准，感受目标肌肉发力，再慢慢加。\n\n我的顺序：热身 → 平板杠铃 → 上斜哑铃 → 夹胸孤立 → 拉伸。每周练两次胸，中间至少歇 48 小时。',
    tags: ['健身', '增肌', '新手教程'], likes: 356, collects: 128, festival: 0,
    comments: [{ author: '瘦竹竿逆袭', avatar: '🥤', text: '收藏了，蛋白粉该怎么冲？' }] },
  { id: 's3', cat: 'keyboard', tall: 1, author: '键盘老李', avatar: '⌨️',
    title: '客制化第一把：Gasket 结构 + 冰淇淋轴，手感直接封神',
    body: '预算 800 搞定一把客制化：套件 + 冰淇淋线性轴 + PBT 球帽。\n\n最惊艳的是 gasket 结构的软弹回馈，打字像踩在棉花上，声音是治愈的「thock」。劝退提醒：入坑毁一生，钱包会哭。',
    tags: ['机械键盘', '客制化', 'thock'], likes: 512, collects: 233, festival: 0,
    comments: [{ author: '秃头码农', avatar: '💻', text: '这套配下来手感确实绝，就是抢套件太难' }, { author: '轴体品鉴家', avatar: '🔧', text: '冰淇淋轴 yyds' }] },
  { id: 's4', cat: 'fishing', author: '夜钓王阿强', avatar: '🎣',
    title: '野河夜钓爆护！红虫拉饵 + 夜光漂的正确用法',
    body: '昨晚在城郊野河守到凌晨两点，鲫鱼板子上了十几条。\n\n关键点：调低钓灵，夜光漂别开太亮惊鱼，红虫挂钩留点须。蚊子是真多，防蚊液带够。',
    tags: ['夜钓', '野钓', '爆护'], likes: 289, collects: 96, festival: 0, comments: [] },
  { id: 's5', cat: 'basketball', tall: 1, author: '三分准', avatar: '🏀',
    title: '野球场生存指南：个子不高怎么打后卫',
    body: '身高 172 打了十年野球，总结三点：\n1）投射要稳，把三分练成饭碗；\n2）速度和变向是你的武器；\n3）会传球的小个子，永远有人愿意跟你一队。\n\n散帅节组个局，评论区约球！',
    tags: ['篮球', '野球场', '后卫'], likes: 445, collects: 152, festival: 1,
    comments: [{ author: '篮板怪', avatar: '🦍', text: '周末城东球场，缺个控卫，来不来？' }] },
  { id: 's6', cat: 'digital', author: '极客阿泽', avatar: '📱',
    title: '2000 块的旧旗舰 vs 全新中端，我劝你买旧旗舰',
    body: '同样的钱，二手旗舰给你更好的屏幕、影像和做工。中端机唯一优势是全新电池和保修。\n\n如果你会看成色、验机、走验机流程，旧旗舰真香。附我的验机 checklist👇',
    tags: ['数码', '手机', '捡漏'], likes: 378, collects: 201, festival: 0,
    comments: [{ author: '数码小白', avatar: '🐣', text: '验机清单能发一份吗跪求' }] },
  { id: 's7', cat: 'car', author: '机油味的风', avatar: '🚗',
    title: '人生第一台手动挡，练到不熄火的第七天',
    body: '半联动是玄学也是肌肉记忆。找个空旷停车场，只用离合不踩油门让车走起来，找到结合点。\n\n第七天终于能在坡道从容起步，那种人车合一的感觉，自动挡真的给不了。',
    tags: ['汽车', '手动挡', '驾驶'], likes: 267, collects: 74, festival: 0, comments: [] },
  { id: 's8', cat: 'cook', tall: 1, author: '颠勺张师傅', avatar: '🍳',
    title: '一个人住也要好好吃饭：15 分钟搞定的黑椒牛柳',
    body: '食材：牛里脊、洋葱、彩椒、黑椒汁。\n\n牛柳逆纹切条，用生抽+淀粉+一点油抓匀腌 10 分钟。热锅热油大火快炒变色盛出，煸洋葱彩椒，回锅淋黑椒汁翻匀。\n\n配一碗白米饭，一个人也能吃得很体面。',
    tags: ['下厨房', '快手菜', '一人食'], likes: 623, collects: 389, festival: 0,
    comments: [{ author: '外卖戒断中', avatar: '🥡', text: '照做了，比外卖香十倍！' }, { author: '厨房杀手', avatar: '🔪', text: '终于有一道我没翻车的菜' }] },
  { id: 's9', cat: 'camp', author: '山系男孩', avatar: '⛺',
    title: '轻量化露营，一个背包装下所有装备',
    body: '钛锅、气炉、蛋卷桌、月亮椅、天幕，全塞进 65L 背包。\n\n重点是取舍：不带用不到的。一杯手冲，一本书，一个下午，山里的风比空调舒服。散帅节适合进山发呆。',
    tags: ['露营', '轻量化', '户外'], likes: 334, collects: 167, festival: 1, comments: [] },
  { id: 's10', cat: 'coffee', tall: 1, author: '手冲咖啡因', avatar: '☕',
    title: '在家手冲入门：三个参数决定一杯的下限',
    body: '粉水比 1:15、水温 90℃、研磨中细。\n\n先闷蒸 30 秒让粉充分排气，再分段注水。新手别纠结器具，先把这三个参数稳定，比换十把手冲壶都有用。',
    tags: ['手冲', '咖啡', '入门'], likes: 401, collects: 245, festival: 0,
    comments: [{ author: '打工人续命', avatar: '🧟', text: '早八靠这杯活着' }] },
  { id: 's11', cat: 'code', author: '秃头码农', avatar: '💻',
    title: '35 岁前想明白的三件事（写给还在卷的兄弟）',
    body: '1）健康是 1，别用命换钱再用钱换命；\n2）副业和技能护城河越早建越好；\n3）别只会写业务代码，抬头看看行业。\n\n散帅节这天，早点下班，去晒晒太阳吧。',
    tags: ['程序员', '职场', '中年'], likes: 892, collects: 456, festival: 1,
    comments: [{ author: '摸鱼战神', avatar: '🐟', text: '第一条说到心坎里了' }, { author: '架构师老王', avatar: '🧓', text: '护城河真的重要，共勉' }] },
  { id: 's12', cat: 'sneaker', author: '球鞋仓管', avatar: '👟',
    title: '收藏党的忠告：鞋是用来穿的，不是供着的',
    body: '开箱即穿，别怕。真正的快乐是穿着心爱的鞋走在路上，而不是塞在鞋墙里发黄。\n\n除氧防潮做好，实战鞋和收藏鞋分开，理性消费不上头。',
    tags: ['球鞋', '收藏', 'sneaker'], likes: 356, collects: 133, festival: 0, comments: [] },
  { id: 's13', cat: 'photo', tall: 1, author: '光影猎人', avatar: '📷',
    title: '扫街三个月，我明白了「决定性瞬间」不是等来的',
    body: '是预判来的。观察光线、找好背景框架，然后耐心等一个人走进你的构图。\n\n器材其次，眼睛才是相机。手机也能扫街，多拍多删，审美自然上来。',
    tags: ['摄影', '扫街', '街拍'], likes: 478, collects: 289, festival: 0,
    comments: [{ author: '胶片痴', avatar: '🎞️', text: '眼睛才是相机，这句话封神' }] },
  { id: 's14', cat: 'fitness', tall: 1, author: '晨跑不迟到', avatar: '🏃',
    title: '从跑 800 米就喘，到跑完半马的一年',
    body: '别追配速，先追时长。用能聊天的速度慢跑，把有氧底子打厚。\n\n每周三练，循序渐进加距离，跑鞋别省，膝盖只有一双。散帅节我用一场晨跑开启。',
    tags: ['跑步', '半马', '有氧'], likes: 512, collects: 198, festival: 1, comments: [] },
  { id: 's15', cat: 'coffee', author: '深夜书房', avatar: '📚',
    title: '男人也需要一个只属于自己的角落',
    body: '一张桌、一盏灯、一杯咖啡、一排书。\n\n不刷手机的一小时，比熬夜到两点更能回血。给自己一个不被打扰的空间，是成年人最低成本的奢侈。',
    tags: ['生活', '独处', '书房'], likes: 445, collects: 234, festival: 0, comments: [] },
  { id: 'b1', cat: 'boysday', tall: 1, author: '男生节应援团', avatar: '🎉',
    title: '6·20 男生节｜今天，对身边的男生说一句「你辛苦了」',
    body: '男生节快乐！\n\n男生不必永远坚强。今天允许自己松弛一点：睡到自然醒、打一把游戏、约兄弟撸个串。\n也别忘了对身边的爸爸、兄弟、朋友说一句——你辛苦了，你值得被在乎。',
    tags: ['男生节', '620', '你辛苦了'], likes: 668, collects: 203, festival: 0,
    comments: [{ author: '沉默老哥', avatar: '🧔', text: '被这句「你辛苦了」整破防了' }] },
  { id: 'b2', cat: 'boysday', author: '礼物挑选官', avatar: '🎁',
    title: '男生节送什么？这几样直男真的会开心',
    body: '机械键盘、球鞋、游戏点卡、剃须刀、一顿烧烤。\n\n别送用不上的摆件，男生要的是「能用、能玩、能吃」。实用才是浪漫。',
    tags: ['男生节', '送礼攻略', '直男'], likes: 432, collects: 288, festival: 0, comments: [] },
  { id: 'b3', cat: 'boysday', tall: 1, author: '老友记', avatar: '🍻',
    title: '男生节，约上三五兄弟撸串喝酒吹牛',
    body: '成年男人的快乐很简单：一桌烧烤、几瓶啤酒、能聊到深夜的老友。\n\n不谈 KPI、不聊房贷，就单纯地做回那个爱笑的少年。今晚谁有空，评论区集合！',
    tags: ['男生节', '兄弟', '聚会'], likes: 389, collects: 97, festival: 0,
    comments: [{ author: '常年加班', avatar: '💼', text: '好久没这么放松了，安排！' }] },
  { id: 'l1', cat: 'lol', tall: 1, author: '中单法王', avatar: '🧙',
    title: '海克斯大乱斗上分：选对英雄就赢一半',
    body: '大乱斗吃阵容和消耗。优先级：远程消耗 > 强开团 > 高回复。\n\n新手推荐艾希、维克托、璐璐，站桩输出压好线别浪走位送人头。出装看阵容：对面高爆发先出抗性，顺风直接叠输出滚雪球。',
    tags: ['英雄联盟', '海克斯大乱斗', '上分'], likes: 721, collects: 355, festival: 0,
    comments: [{ author: '钻石打野', avatar: '🌲', text: '压线意识才是大乱斗的胜负手' }, { author: '辅助之光', avatar: '🛡️', text: '璐璐给队友加速真的救了好多次' }] },
  { id: 'l2', cat: 'lol', author: '版本雷达', avatar: '📡',
    title: '本周海克斯大乱斗英雄强度榜（T0 / T1）',
    body: 'T0：斯维因、婕拉、小炮——消耗拉满，直接劝退对面血线。\nT1：EZ、拉克丝、泽拉斯，手长苟得住。\n\n近战注意：诺手、狼人能开团能 C，但极其怕被风筝，切记别裸冲。',
    tags: ['英雄联盟', '强度榜', '版本答案'], likes: 534, collects: 412, festival: 0, comments: [] },
  { id: 'l3', cat: 'lol', author: '五黑缺一', avatar: '🎮',
    title: '晚八点海克斯大乱斗五黑，缺一个上分搭子',
    body: '黄金以上、有麦、不喷人，只为快乐游戏。\n\n散帅节这周天天开黑，评论区扣「1」，拉你进队。菜没关系，开心最重要，来的都是兄弟！',
    tags: ['英雄联盟', '开黑', '五黑招募'], likes: 298, collects: 66, festival: 0,
    comments: [{ author: '快乐风男', avatar: '😆', text: '1！带我一个' }] },
]

const SEED_HELP = [
  { id: 'h1', type: 'need', author: '刚落地新一线', avatar: '📦', title: '周末求两个搬家帮手，管饭 + 红包', body: '三楼无电梯，家当不多主要是几个大箱子，散帅节兄弟搭把手，管一顿火锅。', city: '杭州', reward: '火锅局', ts: '2小时前' },
  { id: 'h2', type: 'offer', author: '修电脑的老周', avatar: '🔧', title: '免费帮装机 / 重装系统 / 清灰', body: '本人 DIY 十年，散帅节这周末义务帮兄弟们装机清灰，只求带杯奶茶。', city: '成都', reward: '交个朋友', ts: '5小时前' },
  { id: 'h3', type: 'need', author: '备考在逃', avatar: '📖', title: '找个考公自习搭子，互相监督', body: '一个人在家总摸鱼，找个线下图书馆搭子，每天打卡互相盯着。', city: '武汉', reward: '互相监督', ts: '1天前' },
  { id: 'h4', type: 'offer', author: '健身老鸟', avatar: '💪', title: '免费带新手入门撸铁，纠正动作', body: '看不得新手拿大重量瞎练受伤。周中晚上带练，把基础动作教明白，不收钱。', city: '广州', reward: '带练', ts: '1天前' },
  { id: 'h5', type: 'need', author: '钓鱼缺搭子', avatar: '🎣', title: '周六野河夜钓，缺一个搭子拼车', body: '装备我有富余，你带瓶水就行。AA 油费，散帅节一起去河边散个帅。', city: '南京', reward: 'AA油费', ts: '3天前' },
]

module.exports = { SEED_POSTS, SEED_HELP }
